# Generated by Django 5.2.11 on 2026-02-14 00:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/')),
                ('file_hash', models.CharField(max_length=64, null=True, unique=True)),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pending'), ('INDEXED', 'Indexed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('is_indexed', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
